[package]
name = "pencil-box"
version = "0.1.2"
edition = "2021"
description = "A versatile Rust utility library, inspired by JavaScript's Lodash, providing common helper functions for collections, strings, numbers, and more, with no external dependencies."
readme = "README.md"
homepage = "https://github.com/rocketnozzle/pencil-box"
repository = "https://github.com/rocketnozzle/pencil-box"
license = "Apache-2.0"
keywords = ["utility", "lodash", "collections", "helpers"]
categories = ["development-tools::build-utils"]
authors = ["rocketnozzle.io"]

exclude = [
    "tests/*",
    "examples/*",
    "benches/*",
    "test_data/*",
    ".github/*",
    "*.rs.bak",
]

[dependencies]
ahash = "0.8.12"

[dev-dependencies]
rand = "0.8"
